# Generated by Django 2.1.4 on 2019-01-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('filepath', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('isRunning', models.CharField(max_length=20)),
                ('errortype', models.CharField(max_length=100)),
                ('runtime', models.IntegerField()),
                ('memoryused', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_submission', to='compilerApiApp.Submissions'),
        ),
    ]
