# Generated by Django 2.1.4 on 2019-01-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilerApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='user_name',
            new_name='username',
        ),
    ]
