# Generated by Django 2.1.4 on 2019-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilerApiApp', '0002_auto_20190101_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='errortype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='isRunning',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='memoryused',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='runtime',
            field=models.IntegerField(blank=True),
        ),
    ]
