# Generated by Django 2.1.4 on 2019-01-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilerApiApp', '0003_auto_20190101_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='errortype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='isRunning',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='memoryused',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
    ]
