# Generated by Django 2.1.4 on 2019-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilerApiApp', '0004_auto_20190101_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='memoryused',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='runtime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
