# Generated by Django 2.1.4 on 2019-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilerApiApp', '0005_auto_20190101_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='errortype',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='memoryused',
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='runtime',
        ),
        migrations.AddField(
            model_name='files',
            name='errortype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='memoryused',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='runtime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
